"""The sensor: the artifact validates against the vendored schema, every
collector reads what it should and judges nothing, and failures are facts."""

import json
import subprocess
from pathlib import Path

import pytest

from immunis.collectors import redact_text, redact_url, scan
from immunis.config import Config, load as load_config

SCHEMA = json.loads((Path(__file__).resolve().parents[1] / "src" / "immunis" / "artifact.schema.json").read_text())


def git(root: Path, *args: str) -> str:
    return subprocess.run(["git", "-C", str(root), *args], capture_output=True, text=True, check=True).stdout


@pytest.fixture
def checkout(tmp_path):
    """A small git repository with one of everything the collectors read."""
    root = tmp_path
    files = {
        "requirements.txt": "django==5.0\nacme-internal==1.2.0\nrequests>=2\n",
        "requirements-private.txt": "acme-internal==1.2.0\n",
        "Dockerfile": ("FROM python:3.12\nRUN pip install --extra-index-url https://reader:s3cret@pypi.example.com/simple/ -r requirements.txt\n"
                       "RUN PIP_EXTRA_INDEX_URL=\"$(cat /run/secrets/index)\" pip install -r requirements-private.txt\n"),
        "pip.conf": "[global]\nindex-url = https://pypi.org/simple\n",
        ".env": "DEBUG=1\nAPI_TOKEN=abc123realvalue\nSECRET_KEY=${SECRET_KEY}\n",
        ".env.example": "API_TOKEN=<token>\n",
        "secrets.sops.json": '{"a": "ENC[...]", "sops": {"age": [{"recipient": "age1qqqqqqqqqqqqqqqqqqqqqqqq"}]}}\n',
        ".sops.yaml": "creation_rules:\n  - age: age1qqqqqqqqqqqqqqqqqqqqqqqq\n",
        ".github/workflows/deploy.yml": (
            "name: deploy\non:\n  push:\n    branches: [main]\njobs:\n  test:\n    runs-on: ubuntu-latest\n"
            "    steps:\n      - run: pytest\n"
            "  build:\n    runs-on: ubuntu-latest\n    needs: [test]\n"
            "    steps:\n      - uses: actions/checkout@v4\n      - name: Secret scan\n        continue-on-error: true\n        run: |\n          gitleaks detect\n"
            "      # - name: Image scan\n      #   run: trivy image app\n      - name: Deploy\n        if: false\n        run: ./deploy.sh\n"),
        "app/main.py": "# immunis: allow credentials-in-url — fixture for a test\nURL = 'https://x:y@example.com/'\nX = 1\n",
        "app/other.py": "# immunis: allow pip-union-mode\n",
        "vendor/lib.py": "# generated by tool, do not edit\n",
        "immunis.toml": 'private_distributions = ["acme-internal"]\ngenerated_manifest = ".generated.json"\n',
        ".generated.json": "{}",
        "pyproject.toml": '[project]\nname = "widgets"\ndependencies = ["httpx>=0.27", "acme-internal==1.2.0"]\n[project.optional-dependencies]\ndev = ["pytest"]\n',
        "templates/.env.local.j2": "API_TOKEN={{ token }}\n",
        "templates/secrets.sops.json.j2": "{}\n",
    }
    for rel, text in files.items():
        p = root / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(text, encoding="utf-8")
    git(root, "init", "-q", "-b", "main")
    git(root, "config", "user.email", "t@example.com")
    git(root, "config", "user.name", "T")
    git(root, "remote", "add", "origin", "git@github.com:acme/widgets.git")
    import hashlib, json as _json
    manifest = {"vendor/lib.py": hashlib.sha256((root / "vendor" / "lib.py").read_bytes()).hexdigest(),
                "app/other.py": "0" * 64, "gone.py": "1" * 64}
    (root / ".generated.json").write_text(_json.dumps(manifest))
    git(root, "add", "-A")
    git(root, "commit", "-q", "-m", "first")
    (root / "app" / "main.py").write_text("X = 2\nPASSWORD=hunter2\n", encoding="utf-8")
    git(root, "commit", "-q", "-am", "second")
    return root


def artifact_for(root, **kw):
    return scan(root, load_config(root), project="widgets", **kw)


def test_artifact_validates_against_the_vendored_schema(checkout):
    jsonschema = pytest.importorskip("jsonschema")
    base = git(checkout, "rev-parse", "HEAD~1").strip()
    art = artifact_for(checkout, base=base)
    jsonschema.validate(art, SCHEMA)
    # The fixture ran no tests, so the coverage collector declares that it found nothing — a failure, not a zero.
    assert [f["collector"] for f in art["scan"]["failed"]] == ["coverage"]
    assert set(art["scan"]["collectors"]) == {"repository", "files", "python-deps", "indexes", "workflows", "sops", "env", "suppressions", "local-checks", "coverage", "diff"}


def test_repository_and_commit(checkout):
    art = artifact_for(checkout)
    repo = art["facts"]["repository"][0]["fields"]
    assert (repo["forge"], repo["owner"], repo["name"]) == ("github", "acme", "widgets")
    assert repo["tracked_only"] is True and repo["file_count"] == 17
    commit = art["facts"]["commit"][0]
    assert commit["id"] == "commit:" + git(checkout, "rev-parse", "HEAD").strip()
    assert commit["fields"]["message_subject"] == "second" and len(commit["fields"]["parents"]) == 1
    assert art["subject"]["commit"] == commit["fields"]["sha"]


def test_files_are_classified_and_digested(checkout):
    files = {f["fields"]["path"]: f for f in artifact_for(checkout)["facts"]["file"]}
    assert files["Dockerfile"]["fields"]["kind"] == "dockerfile"
    assert files["requirements.txt"]["fields"]["kind"] == "requirements"
    assert files[".env"]["fields"]["kind"] == "env"
    assert files[".github/workflows/deploy.yml"]["fields"]["kind"] == "workflow"
    assert files["app/main.py"]["fields"]["kind"] == "python"
    assert "vendored" in files["vendor/lib.py"]["tags"] and "generated" in files["vendor/lib.py"]["tags"]
    assert len(files["app/main.py"]["fields"]["sha256"]) == 64
    assert all("tracked" in f["tags"] for f in files.values())


def test_dependencies_with_privacy_from_config(checkout):
    deps = {(d["fields"]["file_path"], d["fields"]["name"]): d for d in artifact_for(checkout)["facts"]["dependency_declaration"]}
    public = deps[("requirements.txt", "acme-internal")]
    assert {"private", "public-file", "pinned"} <= set(public["tags"])
    assert deps[("requirements-private.txt", "acme-internal")]["tags"] == ["pinned", "private", "private-file"]
    assert "unpinned" in deps[("requirements.txt", "requests")]["tags"]
    assert deps[("requirements.txt", "django")]["fields"]["spec"] == "==5.0"


def test_index_references_are_redacted(checkout):
    art = artifact_for(checkout)
    refs = {(r["fields"]["file_path"], r["fields"]["line"]): r for r in art["facts"]["index_reference"]}
    docker = refs[("Dockerfile", 2)]
    assert docker["fields"]["url"] == "https://<redacted>@pypi.example.com/simple/"
    assert docker["fields"]["had_credentials"] is True
    assert {"union", "credentialed", "private"} <= set(docker["tags"])
    assert "s3cret" not in json.dumps(art)
    conf = refs[("pip.conf", 2)]
    assert conf["fields"]["kind"] == "index-url" and "public" in conf["tags"] and "union" not in conf["tags"]
    assert {"name": "declared_in", "subject": docker["id"], "object": "file:Dockerfile"} in art["relations"]


def test_workflow_steps_including_commented_and_disabled(checkout):
    art = artifact_for(checkout)
    wf = art["facts"]["workflow"][0]
    assert wf["fields"]["forge"] == "github" and wf["fields"]["jobs"] == ["test", "build"] and "deploy" in wf["tags"]
    jobs = {j["fields"]["name"]: j for j in art["facts"]["workflow_job"]}
    assert jobs["build"]["fields"]["needs"] == ["test"] and jobs["test"]["fields"]["runs_on"] == "ubuntu-latest"
    assert {"name": "needs", "subject": jobs["build"]["id"], "object": jobs["test"]["id"]} in art["relations"]
    steps = {s["fields"]["index"]: s for s in art["facts"]["workflow_step"] if s["fields"]["job"] == "build"}
    assert steps[1]["fields"]["continue_on_error"] is True and "soft-fail" in steps[1]["tags"]
    assert {"name": "in_job", "subject": steps[1]["id"], "object": jobs["build"]["id"]} in art["relations"]
    assert steps[0]["fields"]["uses"] == "actions/checkout@v4"
    assert steps[1]["fields"]["tool"] == "gitleaks" and "scanner" in steps[1]["tags"] and steps[1]["fields"]["enabled"]
    assert steps[2]["fields"]["tool"] == "trivy" and "disabled" in steps[2]["tags"]
    assert steps[3]["fields"]["enabled"] is False and "disabled" in steps[3]["tags"]
    assert "run" not in steps[1]["fields"] and "run_digest" in steps[1]["fields"], "run text never leaves the sensor"


def test_sops_store_and_env_file(checkout):
    art = artifact_for(checkout)
    store = art["facts"]["secret_store"][0]
    assert store["fields"]["recipient_count"] == 1 and "single-recipient" in store["tags"]
    env = {e["fields"]["path"]: e for e in art["facts"]["env_file"]}
    assert ".env.example" not in env
    assert env[".env"]["fields"]["keys"] == ["DEBUG", "API_TOKEN", "SECRET_KEY"]
    assert env[".env"]["fields"]["assigned_secret_keys"] == ["API_TOKEN"]
    assert "abc123realvalue" not in json.dumps(art), "values never leave the collector"


def test_suppressions_are_facts_not_filters(checkout):
    art = artifact_for(checkout)
    sups = {s["fields"]["path"]: s for s in art["facts"]["suppression"]}
    assert sups["app/other.py"]["fields"]["check"] == "pip-union-mode" and "no-reason" in sups["app/other.py"]["tags"]
    assert {"name": "located_in", "subject": sups["app/other.py"]["id"], "object": "file:app/other.py"} in art["relations"]


def test_diff_is_redacted_and_summarised(checkout):
    base = git(checkout, "rev-parse", "HEAD~1").strip()
    art = artifact_for(checkout, base=base)
    change = art["facts"]["change"][0]["fields"]
    assert change["files_changed"] == 1 and change["insertions"] == 2
    assert "hunter2" not in change["diff"] and "PASSWORD= <redacted>" in change["diff"]
    assert art["subject"]["change"] == {"base": base, "head": change["head"]}


def test_without_base_the_diff_is_a_legible_absence(checkout):
    art = artifact_for(checkout)
    assert "change" not in art["facts"]
    assert {"collector": "diff", "reason": "no base ref given; no change record"} in art["scan"]["failed"]


def test_outside_git_still_scans(tmp_path):
    (tmp_path / "requirements.txt").write_text("x==1\n")
    art = scan(tmp_path, Config(), project="loose")
    assert art["facts"]["repository"][0]["fields"]["tracked_only"] is False
    assert any(f["collector"] == "repository" for f in art["scan"]["failed"])
    assert art["facts"]["dependency_declaration"][0]["fields"]["name"] == "x"


def test_redaction_helpers():
    assert redact_url("https://u:p@h/x") == ("https://<redacted>@h/x", True)
    assert redact_url("https://h/x") == ("https://h/x", False)
    assert "topsecret" not in redact_text("+API_TOKEN=topsecret\n+DEBUG=1\n")
    assert "DEBUG=1" in redact_text("+API_TOKEN=topsecret\n+DEBUG=1\n")


def test_findings_ride_along_as_third_party_findings(checkout):
    from immunis.checks import run
    findings = run(checkout, load_config(checkout))
    art = scan(checkout, load_config(checkout), project="widgets", findings=findings)
    tools = {f["fields"]["rule_id"] for f in art["facts"]["third_party_finding"]}
    assert "pip-union-mode" in tools and "private-dep-in-public-requirements" in tools
    assert all(f["fields"]["tool"] == "immunis" for f in art["facts"]["third_party_finding"])


def test_pyproject_dependencies_are_declared(checkout):
    deps = [d for d in artifact_for(checkout)["facts"]["dependency_declaration"] if d["fields"]["file_path"] == "pyproject.toml"]
    by_name = {d["fields"]["name"]: d for d in deps}
    assert by_name["acme-internal"]["fields"]["spec"] == "==1.2.0" and "private" in by_name["acme-internal"]["tags"]
    assert by_name["httpx"]["fields"]["line"] == 3
    assert by_name["pytest"]["id"].endswith(":dev")


def test_templates_of_files_are_not_the_files(checkout):
    art = artifact_for(checkout)
    assert [e["fields"]["path"] for e in art["facts"]["env_file"]] == [".env"]
    assert [s["fields"]["path"] for s in art["facts"]["secret_store"]] == ["secrets.sops.json"]


def test_union_mode_through_an_environment_variable_is_a_fact(checkout):
    refs = [r for r in artifact_for(checkout)["facts"]["index_reference"] if r["fields"]["file_path"] == "Dockerfile"]
    env_form = next(r for r in refs if r["fields"]["line"] == 3)
    assert env_form["fields"]["kind"] == "extra-index-url" and "union" in env_form["tags"]
    assert env_form["fields"]["url"] == "$(cat /run/secrets/index)" and env_form["fields"]["host"] == ""
    assert not {"public", "private"} & set(env_form["tags"]), "no host, no verdict on whose index it is"


CHECK = """#!/bin/sh
printf '[{"rule_id": "missing-testid", "severity": "high", "path": "app/main.py", "line": 1, "message": "no data-testid"}]'
"""


@pytest.fixture
def with_checks(checkout):
    import hashlib, os
    d = checkout / ".immunis" / "checks"
    d.mkdir(parents=True)
    (d / "testids").write_text(CHECK)
    (d / "broken").write_text("#!/bin/sh\nexit 3\n")
    (d / "quiet").write_text("#!/bin/sh\necho ok\n")
    (d / "notes.txt").write_text("not executable, not a check\n")
    for name in ("testids", "broken", "quiet"):
        os.chmod(d / name, 0o755)
    listed = hashlib.sha256((d / "testids").read_bytes()).hexdigest()
    (d / "SHA256SUMS").write_text(f"{listed}  testids\n{'0' * 64}  quiet\n")
    git(checkout, "add", "-A")
    git(checkout, "commit", "-q", "-m", "checks")
    return checkout


def test_local_checks_run_out_of_process_and_are_digested(with_checks):
    jsonschema = pytest.importorskip("jsonschema")
    art = artifact_for(with_checks)
    jsonschema.validate(art, SCHEMA)
    checks = {c["fields"]["check"]: c for c in art["facts"]["local_check"]}
    assert set(checks) == {"testids", "broken", "quiet"}
    assert checks["testids"]["tags"] == [] and checks["testids"]["fields"]["findings"] == 1
    assert checks["testids"]["fields"]["listed_sha256"] == checks["testids"]["fields"]["sha256"]
    assert "modified" in checks["quiet"]["tags"], "listed digest differs"
    assert "unlisted" in checks["broken"]["tags"] and "failed" in checks["broken"]["tags"]
    assert checks["broken"]["fields"]["exit_code"] == 3
    assert any(f["collector"] == "local-checks" and "notes.txt" in f["reason"] for f in art["scan"]["failed"])


def test_local_findings_are_ours(with_checks):
    art = artifact_for(with_checks)
    finding = art["facts"]["local_finding"][0]
    assert finding["fields"]["rule_id"] == "missing-testid" and "high" in finding["tags"]
    assert {"name": "found_by", "subject": finding["id"], "object": "check:testids"} in art["relations"]
    assert {"name": "located_in", "subject": finding["id"], "object": "file:app/main.py"} in art["relations"]


def test_no_checks_directory_means_no_records_and_no_failure(checkout):
    art = artifact_for(checkout)
    assert "local_check" not in art["facts"]
    assert not any(f["collector"] == "local-checks" for f in art["scan"]["failed"])


def test_generated_manifest_makes_hand_edits_a_fact(checkout):
    art = artifact_for(checkout)
    files = {f["fields"]["path"]: f for f in art["facts"]["file"]}
    assert {"listed", "generated"} <= set(files["vendor/lib.py"]["tags"]) and "hand-edited" not in files["vendor/lib.py"]["tags"]
    assert "hand-edited" in files["app/other.py"]["tags"] and files["app/other.py"]["fields"]["listed_sha256"] == "0" * 64
    m = art["facts"]["generated_manifest"][0]
    assert m["fields"]["format"] == "json" and m["fields"]["entries"] == 3 and m["fields"]["missing"] == ["gone.py"]
    assert "incomplete" in m["tags"]


def test_absent_manifest_is_a_legible_failure(tmp_path):
    (tmp_path / "immunis.toml").write_text('generated_manifest = "nope.json"\n')
    art = scan(tmp_path, load_config(tmp_path), project="x")
    assert "generated_manifest" not in art["facts"]
    assert any(f["collector"] == "files" and "nope.json" in f["reason"] for f in art["scan"]["failed"])


def test_coverage_report_from_json_file(checkout):
    (checkout / "coverage.json").write_text(json.dumps({
        "meta": {"timestamp": "2026-10-07T06:00:00"},
        "totals": {"percent_covered": 81.234, "num_statements": 1000, "covered_lines": 812}}))
    art = artifact_for(checkout)
    (cov,) = art["facts"]["coverage_report"]
    assert cov["id"] == "coverage:coverage.py"
    assert cov["fields"] == {"tool": "coverage.py", "total_percent": 8123, "lines_total": 1000, "lines_covered": 812,
                             "measured_at": "2026-10-07T06:00:00Z", "source": "file"}
    assert "coverage" in art["scan"]["collectors"] and not [f for f in art["scan"]["failed"] if f["collector"] == "coverage"]


def test_coverage_report_from_cobertura_xml(checkout):
    (checkout / "coverage.xml").write_text(
        '<?xml version="1.0" ?>\n<!-- Generated by coverage.py: https://coverage.readthedocs.io/en/7.6.1 -->\n'
        '<coverage version="7.6.1" timestamp="1791352800000" lines-valid="200" lines-covered="150" line-rate="0.75" '
        'branches-covered="0" branches-valid="0" branch-rate="0" complexity="0"></coverage>\n')
    art = artifact_for(checkout)
    (cov,) = art["facts"]["coverage_report"]
    assert cov["fields"]["tool"] == "coverage.py" and cov["fields"]["total_percent"] == 7500
    assert cov["fields"]["lines_total"] == 200 and cov["fields"]["lines_covered"] == 150
    assert cov["fields"]["measured_at"] == "2026-10-07T06:00:00Z" and cov["fields"]["source"] == "file"


def test_no_coverage_is_a_collector_failure_not_a_zero(checkout):
    art = artifact_for(checkout)
    assert "coverage_report" not in art["facts"]
    assert {"collector": "coverage", "reason": "no coverage report found (coverage.json, coverage.xml or .coverage)"} in art["scan"]["failed"]
