"""The sensor: collectors that read a checkout and emit facts.

A collector reads the checkout and returns records and relations. It judges
nothing: whether a fact is acceptable is a rule somewhere else. The artifact
this module builds is described by `artifact.schema.json` beside it (a
vendored copy of the consumer's schema; the sensor pins the major it emits).

Rules, in order of how much they matter:

- **Nothing here raises.** A collector that fails is recorded in the
  envelope's `failed` list with a reason and the scan continues; absence must
  be legible, never silent.
- **Deterministic.** Ids come from paths and lines, never counters, so two
  scans of the same commit produce the same ids and a diff of scans means
  something.
- **Redact before emit.** A URL's credentials become `<redacted>` inside the
  collector that read them; `.env` files contribute key names, never values.
- **Bounded.** Each collector enforces its own caps and says in `failed` when
  it hit one.
- **Stdlib only**, like the rest of the package.
"""

from __future__ import annotations

import hashlib
import re
import subprocess
from datetime import datetime, timezone
from pathlib import Path

from . import __version__
from .repo import Repo

SCHEMA_VERSION = "1.1"
FILE_CAP = 20_000
LIST_CAP = 1_000
DIFF_CAP_BYTES = 512 * 1024
CHECKS_DIR = Path(".immunis/checks")
CHECK_TIMEOUT_SECONDS = 300
CHECK_OUTPUT_CAP = 4 * 1024 * 1024

_CREDENTIALED = re.compile(r"(?P<scheme>https?://)(?P<user>[^/\s:@]+):(?P<password>[^/\s@]+)@")
_REQ_LINE = re.compile(r"^\s*(?P<name>[A-Za-z0-9][A-Za-z0-9._-]*)\s*(?P<extras>\[[^\]]*\])?\s*(?P<spec>[<>=!~][^;#]*)?")
_SECRET_KEY = re.compile(
    r"^\s*(?:export\s+)?([A-Z0-9_]*(?:SECRET|PASSWORD|TOKEN|API_KEY|PRIVATE_KEY|DSN|CREDENTIAL)[A-Z0-9_]*)\s*=\s*(.+?)\s*$"
)
_ENV_KEY = re.compile(r"^\s*(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=")
_PLACEHOLDER = re.compile(
    r"^(?:[\"']?\s*[\"']?|\$\{?[A-Za-z_].*|<.*>|x+|changeme|placeholder|todo|your[-_].*|\.\.\.)$", re.IGNORECASE)
_SUPPRESSION = re.compile(r"immunis:\s*allow\s+(?P<check>[a-z0-9][a-z0-9-]*)\s*(?P<reason>.*)$")
_GENERATED = re.compile(r"(generated by|do not edit|auto-generated|this file is generated)", re.IGNORECASE)
_SCANNER_TOOLS = ("gitleaks", "trivy", "pip-audit", "immunis", "semgrep", "bandit", "grype", "snyk")
_PUBLIC_INDEX_HOSTS = frozenset({"pypi.org", "files.pythonhosted.org", "test.pypi.org"})
# A template of a file is not the file: `.env.local.j2` assigns nothing and
# `.sops.yaml.j2` protects nothing. Collectors that read the thing itself skip these.
_TEMPLATE_SUFFIXES = (".j2", ".jinja", ".jinja2", ".tmpl", ".template", ".example", ".sample", ".dist")


def _is_template(rel: Path) -> bool:
    return rel.name.endswith(_TEMPLATE_SUFFIXES)


# --- helpers -----------------------------------------------------------------------

def _now() -> str:
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def record(id: str, tags: list[str], **fields) -> dict:
    return {"id": id, "tags": sorted(set(tags)), "fields": fields}


def relation(name: str, subject: str, object: str) -> dict:
    return {"name": name, "subject": subject, "object": object}


def redact_url(url: str) -> tuple[str, bool]:
    """`scheme://user:pass@host` → `scheme://<redacted>@host`, and whether anything was there."""
    had = False

    def sub(m):
        nonlocal had
        had = True
        return f"{m.group('scheme')}<redacted>@"

    return _CREDENTIALED.sub(sub, url), had


def redact_text(text: str) -> str:
    """The same redaction over free text (the diff): URL credentials and
    credential-looking assignments."""
    text, _ = redact_url(text)
    out = []
    for line in text.splitlines(keepends=True):
        m = _SECRET_KEY.match(line.lstrip("+- "))
        if m:
            value = m.group(2).strip().strip("\"'")
            if value and not _PLACEHOLDER.match(value):
                line = line[:line.index("=") + 1] + " <redacted>\n"
        out.append(line)
    return "".join(out)


def _git(root: Path, *args: str, timeout: int = 30) -> str | None:
    try:
        r = subprocess.run(["git", "-C", str(root), *args], capture_output=True, timeout=timeout, check=False)
    except (OSError, subprocess.SubprocessError):
        return None
    if r.returncode != 0:
        return None
    return r.stdout.decode("utf-8", "replace")


def _normalise(name: str) -> str:
    return name.strip().lower().replace("_", "-").replace(".", "-")


def _kind_of(rel: Path) -> str:
    name, suffix = rel.name, rel.suffix.lower()
    if name in ("Dockerfile", "Containerfile") or name.startswith("Dockerfile."):
        return "dockerfile"
    if ".sops." in name or name == ".sops.yaml":
        return "sops"
    if name == ".env" or name.startswith(".env."):
        return "env"
    if name.startswith("requirements") and suffix == ".txt":
        return "requirements"
    if "workflows" in rel.parts and suffix in (".yml", ".yaml"):
        return "workflow"
    if suffix == ".py":
        return "python"
    if suffix in (".toml", ".cfg", ".ini", ".yml", ".yaml", ".json", ".conf"):
        return "config"
    if suffix in (".png", ".jpg", ".jpeg", ".gif", ".ico", ".pdf", ".zip", ".gz", ".whl", ".so", ".pyc", ".woff", ".woff2", ".ttf", ".sqlite3", ".db"):
        return "binary"
    return "text"


# --- the collectors --------------------------------------------------------------------

class Collection:
    """What a scan accumulates: records by kind, relations, failures."""

    def __init__(self):
        self.facts: dict[str, list[dict]] = {}
        self.relations: list[dict] = []
        self.failed: list[dict] = []
        self.ran: list[str] = []

    def add(self, kind: str, rec: dict) -> None:
        self.facts.setdefault(kind, []).append(rec)

    def relate(self, name: str, subject: str, object: str) -> None:
        self.relations.append(relation(name, subject, object))

    def fail(self, collector: str, reason: str) -> None:
        self.failed.append({"collector": collector, "reason": reason})

    def file_ids(self) -> set[str]:
        return {r["id"] for r in self.facts.get("file", [])}


def collect_repository(repo: Repo, config, c: Collection, ctx: dict) -> None:
    root = repo.root
    forge = owner = name = ""
    remote = (_git(root, "remote", "get-url", "origin") or "").strip()
    if remote:
        m = re.search(r"(?:@|://)([^/:]+)[:/]([^/]+)/([^/]+?)(?:\.git)?/?$", remote)
        if m:
            host, owner, name = m.group(1), m.group(2), m.group(3)
            forge = "github" if "github.com" in host else ("gitlab" if "gitlab" in host else "gitea" if "gitea" in host else host)
    if not name:
        name = root.name
    default_branch = (_git(root, "symbolic-ref", "--short", "refs/remotes/origin/HEAD") or "").strip().split("/")[-1] or "main"
    tracked_only = repo._tracked is not None
    ctx["repository"] = {"forge": forge, "owner": owner, "name": name}
    c.add("repository", record(f"repository:{owner}/{name}" if owner else f"repository:{name}", [],
                               forge=forge, owner=owner, name=name, default_branch=default_branch,
                               file_count=0, tracked_only=tracked_only))
    sha = (_git(root, "rev-parse", "HEAD") or "").strip()
    if not sha:
        c.fail("repository", "not a git repository, or no commits: no commit record")
        return
    ctx["commit"] = sha
    parents = (_git(root, "log", "-1", "--format=%P") or "").split()
    authored = (_git(root, "log", "-1", "--format=%aI") or "").strip()
    author = (_git(root, "log", "-1", "--format=%an") or "").strip()
    subject = (_git(root, "log", "-1", "--format=%s") or "").strip()
    fields = dict(sha=sha, authored_at=authored, message_subject=subject, parents=parents[:LIST_CAP])
    if author:
        fields["author_name"] = author
    c.add("commit", record(f"commit:{sha}", ["merge"] if len(parents) > 1 else [], **fields))


def collect_files(repo: Repo, config, c: Collection, ctx: dict) -> None:
    count = 0
    for rel in repo.walk():
        count += 1
        if count > FILE_CAP:
            continue
        p = repo.root / rel
        try:
            data = p.read_bytes()
            executable = bool(p.stat().st_mode & 0o111)
        except OSError as e:
            c.fail("files", f"{rel}: {e.__class__.__name__}")
            continue
        kind = _kind_of(rel)
        tags = []
        if repo._tracked is not None:
            tags.append("tracked")
        if any(part in ("vendor", "vendored", "third_party", "third-party") for part in rel.parts[:-1]):
            tags.append("vendored")
        if kind != "binary" and _GENERATED.search(data[:2000].decode("utf-8", "replace")):
            tags.append("generated")
        c.add("file", record(f"file:{rel.as_posix()}", tags, path=rel.as_posix(), size=len(data),
                             sha256=hashlib.sha256(data).hexdigest(), kind=kind, executable=executable))
    for r in c.facts.get("repository", []):
        r["fields"]["file_count"] = count
    if count > FILE_CAP:
        c.fail("files", f"{count} files; only the first {FILE_CAP} are listed")


def _requirements_files(repo: Repo):
    for rel in repo.walk(suffixes={".txt"}):
        if rel.name.startswith("requirements") and not _is_template(rel):
            yield rel


def _pyproject_dependencies(repo: Repo):
    """(rel, line, name, spec, extras, group) for `[project]` dependencies and
    optional-dependencies of every pyproject.toml. Lines are found by
    searching the text for the requirement, since tomllib keeps none."""
    import tomllib
    for rel in repo.walk(names={"pyproject.toml"}):
        text = repo.read(*rel.parts)
        try:
            data = tomllib.loads(text)
        except tomllib.TOMLDecodeError:
            continue
        project = data.get("project") or {}
        groups = [("", project.get("dependencies") or [])]
        groups += [(g, deps) for g, deps in (project.get("optional-dependencies") or {}).items()]
        lines = text.splitlines()
        for group, deps in groups:
            for req in deps:
                if not isinstance(req, str):
                    continue
                line = next((n for n, l in enumerate(lines, 1) if req in l), 0)
                yield rel, line, req, group


def collect_python_deps(repo: Repo, config, c: Collection, ctx: dict) -> None:
    private = getattr(config, "private_distributions", frozenset())
    files = c.file_ids()
    for rel, n, req, group in _pyproject_dependencies(repo):
        m = _REQ_LINE.match(req)
        if not m:
            continue
        name = _normalise(m.group("name"))
        spec = (m.group("spec") or "").strip()
        extras = [x.strip() for x in (m.group("extras") or "").strip("[]").split(",") if x.strip()]
        tags = ["public-file", "pinned" if spec.startswith("==") else "unpinned"] + (["private"] if name in private else [])
        dep_id = f"dep:{rel.as_posix()}:{n}:{name}" + (f":{group}" if group else "")
        c.add("dependency_declaration", record(dep_id, tags, name=name, spec=spec, extras=extras, manager="pip",
                                               file_path=rel.as_posix(), line=n, direct=True))
        if f"file:{rel.as_posix()}" in files:
            c.relate("declared_in", dep_id, f"file:{rel.as_posix()}")
    for rel in _requirements_files(repo):
        file_id = f"file:{rel.as_posix()}"
        private_file = "private" in rel.name
        for n, line in repo.lines(rel):
            text = line.split("#", 1)[0].strip()
            if not text or text.startswith("-"):
                continue
            m = _REQ_LINE.match(text)
            if not m:
                continue
            name = _normalise(m.group("name"))
            spec = (m.group("spec") or "").strip()
            extras = [x.strip() for x in (m.group("extras") or "").strip("[]").split(",") if x.strip()]
            tags = ["private-file" if private_file else "public-file",
                    "pinned" if spec.startswith("==") else "unpinned"]
            if name in private:
                tags.append("private")
            dep_id = f"dep:{rel.as_posix()}:{n}"
            c.add("dependency_declaration", record(dep_id, tags, name=name, spec=spec, extras=extras, manager="pip",
                                                   file_path=rel.as_posix(), line=n, direct=True))
            if file_id in files:
                c.relate("declared_in", dep_id, file_id)


_INDEX_NAMES = frozenset({"Dockerfile", "Containerfile", "pip.conf", "pip.ini", "setup.cfg", "tox.ini"})
_INDEX_SUFFIXES = frozenset({".yml", ".yaml", ".sh", ".toml", ".cfg", ".txt"})
_INDEX_PATTERNS = (
    (re.compile(r"--extra-index-url[=\s]+(\S+)"), "extra-index-url"),
    (re.compile(r"--index-url[=\s]+(\S+)"), "index-url"),
    (re.compile(r"--find-links[=\s]+(\S+)"), "find-links"),
    (re.compile(r"^\s*extra-index-url\s*=\s*(\S+)"), "extra-index-url"),
    (re.compile(r"^\s*index-url\s*=\s*(\S+)"), "index-url"),
    # The environment-variable forms configure the same thing as the flags,
    # and often carry a secret reference rather than a literal URL; the fact
    # that an extra index is configured stands either way.
    (re.compile(r"(?:^|\s)(?:export\s+)?PIP_EXTRA_INDEX_URL\s*=\s*(\"[^\"]*\"|'[^']*'|\S+)"), "extra-index-url"),
    (re.compile(r"(?:^|\s)(?:export\s+)?PIP_INDEX_URL\s*=\s*(\"[^\"]*\"|'[^']*'|\S+)"), "index-url"),
    (re.compile(r"^\s*url\s*=\s*[\"'](\S+?)[\"']"), "config"),
)


def collect_indexes(repo: Repo, config, c: Collection, ctx: dict) -> None:
    files = c.file_ids()
    for rel in repo.walk():
        if rel.name not in _INDEX_NAMES and rel.suffix not in _INDEX_SUFFIXES:
            continue
        if rel.suffix in (".md", ".rst") or _is_template(rel):
            continue
        file_id = f"file:{rel.as_posix()}"
        for n, line in repo.lines(rel):
            if line.lstrip().startswith("#"):
                continue
            for pattern, kind in _INDEX_PATTERNS:
                m = pattern.search(line)
                if not m:
                    continue
                raw = m.group(1).strip("\"'")
                literal = raw.startswith(("http://", "https://"))
                if not literal and "PIP_" not in pattern.pattern:
                    continue
                url, had = redact_url(raw)
                host = re.sub(r"^https?://(?:[^@/]+@)?([^/:]+).*$", r"\1", url) if literal else ""
                tags = []
                if kind == "extra-index-url":
                    tags.append("union")
                if had:
                    tags.append("credentialed")
                if literal:
                    tags.append("public" if host in _PUBLIC_INDEX_HOSTS else "private")
                ref_id = f"index:{rel.as_posix()}:{n}"
                c.add("index_reference", record(ref_id, tags, url=url, host=host, kind=kind,
                                                file_path=rel.as_posix(), line=n, had_credentials=had))
                if file_id in files:
                    c.relate("declared_in", ref_id, file_id)
                break


def _parse_workflow(text: str) -> dict:
    """The `jobs → steps` shape of a workflow file, read by indentation.

    The stdlib has no YAML reader. This follows the one shape CI workflows
    take — top-level `name`, `on`, `jobs`; each job a mapping with `steps`, a
    list of mappings — and raises ValueError on anything it cannot follow,
    which the caller records as a failure rather than guessing.
    """
    lines = text.splitlines()
    name, triggers, jobs = "", [], {}
    i = 0
    while i < len(lines):
        raw = lines[i]
        line = raw.split(" #", 1)[0].rstrip() if not raw.lstrip().startswith("#") else ""
        if not line.strip():
            i += 1
            continue
        indent = len(line) - len(line.lstrip())
        if indent == 0:
            key, _, value = line.partition(":")
            key = key.strip()
            if key == "name":
                name = value.strip().strip("\"'")
            elif key in ("on", "true"):
                if value.strip() and not value.strip().startswith("["):
                    triggers = [value.strip()]
                elif value.strip():
                    triggers = [t.strip() for t in value.strip().strip("[]").split(",") if t.strip()]
                else:
                    j = i + 1
                    while j < len(lines) and (not lines[j].strip() or lines[j].startswith((" ", "\t"))):
                        s = lines[j].strip()
                        if s and not s.startswith(("-", "#")) and len(lines[j]) - len(lines[j].lstrip()) == 2:
                            triggers.append(s.split(":")[0])
                        j += 1
            elif key == "jobs":
                i = _parse_jobs(lines, i + 1, jobs)
                continue
        i += 1
    return {"name": name, "triggers": triggers, "jobs": jobs}


def _parse_jobs(lines: list[str], i: int, jobs: dict) -> int:
    current = None
    while i < len(lines):
        raw = lines[i]
        if raw.strip() and not raw.startswith((" ", "\t")):
            return i                          # next top-level key
        stripped = raw.split(" #", 1)[0].rstrip()
        commented = raw.lstrip().startswith("#")
        indent = len(raw) - len(raw.lstrip())
        if not commented and indent == 2 and stripped.strip().endswith(":") and not stripped.strip().startswith("-"):
            current = stripped.strip()[:-1]
            jobs[current] = []
            i += 1
            continue
        if current is not None and stripped.strip() == "steps:" and indent == 4:
            i = _parse_steps(lines, i + 1, jobs[current])
            continue
        if current is not None and raw.lstrip("# ").startswith("steps:") and commented:
            i = _parse_steps(lines, i + 1, jobs[current], all_disabled=True)
            continue
        i += 1
    return i


def _parse_steps(lines: list[str], i: int, steps: list, all_disabled: bool = False) -> int:
    step = None
    while i < len(lines):
        raw = lines[i]
        text = raw.lstrip("# ") if raw.lstrip().startswith("#") else raw
        commented = raw.lstrip().startswith("#")
        indent = len(raw) - len(raw.lstrip())
        if raw.strip() and indent <= 4 and not raw.lstrip().startswith("-") and not commented:
            return i                          # next job key or top level
        stripped = text.strip()
        if stripped.startswith("- "):
            step = {"name": "", "uses": None, "run": "", "enabled": not (commented or all_disabled), "if": None}
            steps.append(step)
            stripped = stripped[2:]
        if step is None or not stripped:
            i += 1
            continue
        key, sep, value = stripped.partition(":")
        key = key.strip()
        if sep and key in ("name", "uses", "if", "run"):
            value = value.strip()
            if key == "run" and value in ("|", ">", "|-", ">-"):
                block, j = [], i + 1
                base = None
                while j < len(lines) and (not lines[j].strip() or (len(lines[j]) - len(lines[j].lstrip())) > indent):
                    if lines[j].strip():
                        base = base if base is not None else len(lines[j]) - len(lines[j].lstrip())
                        block.append(lines[j][base:] if len(lines[j]) >= base else lines[j].strip())
                    j += 1
                step["run"] = "\n".join(block)
                i = j
                continue
            if key == "run":
                step["run"] = value
            elif key == "if":
                step["if"] = value
                if value.strip().strip("\"'").lower() == "false":
                    step["enabled"] = False
            else:
                step[key] = value.strip("\"'")
        i += 1
    return i


def collect_workflows(repo: Repo, config, c: Collection, ctx: dict) -> None:
    for rel in repo.walk(suffixes={".yml", ".yaml"}):
        if len(rel.parts) < 3 or rel.parts[0] not in (".gitea", ".github") or rel.parts[1] != "workflows":
            continue
        try:
            wf = _parse_workflow(repo.read(*rel.parts))
        except Exception as e:  # noqa: BLE001 — a failure is a fact, not a crash
            c.fail("workflows", f"{rel}: could not follow the file ({e.__class__.__name__})")
            continue
        forge = "gitea" if rel.parts[0] == ".gitea" else "github"
        wf_id = f"workflow:{rel.as_posix()}"
        lname = (wf["name"] or rel.stem).lower()
        tags = [t for t in ("deploy", "publish", "test") if t in lname or t in rel.stem.lower()]
        c.add("workflow", record(wf_id, tags, path=rel.as_posix(), forge=forge, name=wf["name"],
                                 triggers=wf["triggers"][:LIST_CAP], jobs=list(wf["jobs"])[:LIST_CAP]))
        for job, steps in wf["jobs"].items():
            for idx, s in enumerate(steps):
                haystack = f"{s['uses'] or ''} {s['run']} {s['name']}".lower()
                tool = next((t for t in _SCANNER_TOOLS if t in haystack), None)
                fields = dict(workflow_path=rel.as_posix(), job=job, index=idx, name=s["name"], enabled=s["enabled"])
                if s["uses"]:
                    fields["uses"] = s["uses"]
                if s["run"]:
                    fields["run_digest"] = hashlib.sha256(s["run"].encode()).hexdigest()
                if tool:
                    fields["tool"] = tool
                stags = []
                if tool:
                    stags.append("scanner")
                if not s["enabled"]:
                    stags.append("disabled")
                step_id = f"step:{rel.as_posix()}:{job}:{idx}"
                c.add("workflow_step", record(step_id, stags, **fields))
                c.relate("part_of", step_id, wf_id)


def collect_sops(repo: Repo, config, c: Collection, ctx: dict) -> None:
    files = c.file_ids()
    recovery = frozenset(getattr(config, "recovery_recipients", ()) or ())
    stores = [rel for rel in repo.walk() if ".sops." in rel.name and rel.name != ".sops.yaml" and not _is_template(rel)]
    for rel in stores:
        text = repo.read(*rel.parts)
        recipients = sorted(set(re.findall(r"age1[0-9a-z]{10,}", text)))
        if not recipients and repo.exists(".sops.yaml"):
            recipients = sorted(set(re.findall(r"age1[0-9a-z]{10,}", repo.read(".sops.yaml"))))
        tags = ["single-recipient"] if len(recipients) < 2 else []
        if repo._tracked is not None:
            tags.append("tracked")
        store_id = f"store:{rel.as_posix()}"
        c.add("secret_store", record(store_id, tags, path=rel.as_posix(), kind="sops",
                                     recipient_count=len(recipients), recipients=recipients[:LIST_CAP],
                                     has_master_key=bool(recovery & set(recipients))))
        file_id = f"file:{rel.as_posix()}"
        if file_id in files:
            c.relate("declared_in", store_id, file_id)


def collect_env(repo: Repo, config, c: Collection, ctx: dict) -> None:
    files = c.file_ids()
    for rel in repo.walk():
        name = rel.name
        if not (name == ".env" or name.startswith(".env.")) or _is_template(rel):
            continue
        keys, secret_keys = [], []
        for n, line in repo.lines(rel):
            m = _ENV_KEY.match(line)
            if not m:
                continue
            keys.append(m.group(1))
            s = _SECRET_KEY.match(line)
            if s:
                value = s.group(2).strip().strip("\"'")
                if value and not _PLACEHOLDER.match(value):
                    secret_keys.append(s.group(1))
        tracked = repo._tracked is not None
        tags = (["tracked"] if tracked else []) + (["assigns-secrets"] if secret_keys else [])
        env_id = f"env:{rel.as_posix()}"
        c.add("env_file", record(env_id, tags, path=rel.as_posix(), tracked=tracked,
                                 keys=keys[:LIST_CAP], assigned_secret_keys=secret_keys[:LIST_CAP]))
        file_id = f"file:{rel.as_posix()}"
        if file_id in files:
            c.relate("declared_in", env_id, file_id)


def collect_suppressions(repo: Repo, config, c: Collection, ctx: dict) -> None:
    files = c.file_ids()
    for rel in repo.walk():
        if _kind_of(rel) == "binary":
            continue
        file_id = f"file:{rel.as_posix()}"
        for n, line in repo.lines(rel):
            m = _SUPPRESSION.search(line)
            if not m:
                continue
            reason = m.group("reason").strip().lstrip("-—:").strip()
            tags = [] if reason else ["no-reason"]
            sup_id = f"allow:{rel.as_posix()}:{n}"
            c.add("suppression", record(sup_id, tags, check=m.group("check"), path=rel.as_posix(), line=n,
                                        scope="line", reason=reason))
            if file_id in files:
                c.relate("located_in", sup_id, file_id)


def collect_diff(repo: Repo, config, c: Collection, ctx: dict) -> None:
    base, head = ctx.get("base"), ctx.get("commit")
    if not base:
        c.fail("diff", "no base ref given; no change record")
        return
    stat = _git(repo.root, "diff", "--numstat", f"{base}..{head or 'HEAD'}")
    raw = _git(repo.root, "diff", "--no-color", "-U3", f"{base}..{head or 'HEAD'}", timeout=120)
    if stat is None or raw is None:
        c.fail("diff", f"git diff {base}..{head or 'HEAD'} failed")
        return
    files_changed = insertions = deletions = 0
    for line in stat.splitlines():
        parts = line.split("\t")
        if len(parts) == 3:
            files_changed += 1
            insertions += int(parts[0]) if parts[0].isdigit() else 0
            deletions += int(parts[1]) if parts[1].isdigit() else 0
    diff = redact_text(raw)
    omitted: list[str] = []
    truncated = False
    if len(diff.encode("utf-8")) > DIFF_CAP_BYTES:
        truncated = True
        chunks = re.split(r"(?m)^(?=diff --git )", diff)
        chunks = [ch for ch in chunks if ch]
        chunks.sort(key=len, reverse=True)
        kept = []
        total = 0
        for ch in chunks:
            path = re.match(r"diff --git a/(\S+)", ch)
            if total + len(ch.encode()) > DIFF_CAP_BYTES or "Binary files" in ch[:400]:
                omitted.append(path.group(1) if path else "?")
                continue
            kept.append(ch)
            total += len(ch.encode())
        diff = "".join(kept)
    tags = ["truncated"] if truncated else []
    change_id = f"change:{base}..{head or 'HEAD'}"
    c.add("change", record(change_id, tags, base=base, head=head or "HEAD", files_changed=files_changed,
                           insertions=insertions, deletions=deletions, diff=diff, truncated=truncated,
                           omitted_files=omitted[:LIST_CAP]))
    ctx["change"] = {"base": base, "head": head or "HEAD"}


def _listed_digests(repo: Repo) -> dict[str, str]:
    """`.immunis/checks/SHA256SUMS` in sha256sum's own format: `<hex>  <name>`."""
    out = {}
    for line in repo.read(*(CHECKS_DIR / "SHA256SUMS").parts).splitlines():
        parts = line.split()
        if len(parts) >= 2 and re.fullmatch(r"[0-9a-f]{64}", parts[0]):
            out[parts[-1].lstrip("*")] = parts[0]
    return out


def _parse_findings(stdout: bytes) -> list[dict]:
    """The findings contract: a JSON list on stdout, each item with rule_id
    (or rule), severity, message, and optionally path and line. Anything
    else on stdout means no findings; the digest still records it."""
    import json
    text = stdout.decode("utf-8", "replace").strip()
    if not text.startswith("["):
        return []
    try:
        items = json.loads(text)
    except ValueError:
        return []
    out = []
    for item in items if isinstance(items, list) else []:
        if not isinstance(item, dict):
            continue
        rule = str(item.get("rule_id") or item.get("rule") or item.get("check") or "").strip()
        if not rule:
            continue
        out.append({"rule_id": rule, "severity": str(item.get("severity") or "info").lower(),
                    "message": str(item.get("message") or item.get("summary") or ""),
                    "path": item.get("path"), "line": item.get("line")})
    return out


def collect_local_checks(repo: Repo, config, c: Collection, ctx: dict) -> None:
    """Every executable under .immunis/checks/ is a check the repository
    carries; it runs out of process with the checkout as its working
    directory, and what it said is recorded, never interpreted. A
    SHA256SUMS file beside them, written by whatever generated the checks,
    makes a modified or unlisted check a fact."""
    directory = repo.root / CHECKS_DIR
    if not directory.is_dir():
        return
    listed = _listed_digests(repo)
    files = c.file_ids()
    severities = ("critical", "high", "medium", "low", "info")
    for path in sorted(directory.iterdir()):
        if not path.is_file() or path.name == "SHA256SUMS" or path.name.startswith("."):
            continue
        rel = path.relative_to(repo.root)
        data = path.read_bytes()
        digest = hashlib.sha256(data).hexdigest()
        tags = []
        if path.name in listed:
            if listed[path.name] != digest:
                tags.append("modified")
        elif listed:
            tags.append("unlisted")
        if not (path.stat().st_mode & 0o111):
            c.fail("local-checks", f"{rel}: not executable; not run")
            continue
        started = datetime.now(timezone.utc)
        try:
            r = subprocess.run([str(path)], cwd=str(repo.root), capture_output=True,
                               timeout=CHECK_TIMEOUT_SECONDS, check=False)
            exit_code, stdout = r.returncode, r.stdout[:CHECK_OUTPUT_CAP]
        except subprocess.TimeoutExpired:
            exit_code, stdout = 124, b""
            c.fail("local-checks", f"{rel}: timed out after {CHECK_TIMEOUT_SECONDS}s")
        except OSError as e:
            exit_code, stdout = 126, b""
            c.fail("local-checks", f"{rel}: could not run ({e.__class__.__name__})")
        duration = int((datetime.now(timezone.utc) - started).total_seconds() * 1000)
        findings = _parse_findings(stdout) if exit_code == 0 else []
        if exit_code != 0:
            tags.append("failed")
        check_id = f"check:{path.name}"
        fields = dict(check=path.name, path=rel.as_posix(), sha256=digest, exit_code=exit_code, duration_ms=duration,
                      stdout_digest=hashlib.sha256(stdout).hexdigest(), findings=len(findings))
        if path.name in listed:
            fields["listed_sha256"] = listed[path.name]
        c.add("local_check", record(check_id, tags, **fields))
        for f in findings:
            fp = hashlib.sha256(f"{path.name}|{f['rule_id']}|{f['path']}|{f['line']}|{f['message']}".encode()).hexdigest()[:16]
            ff = dict(check=path.name, rule_id=f["rule_id"], severity=f["severity"], message=f["message"], fingerprint=fp)
            if f["path"]:
                ff["path"] = str(f["path"])
            if isinstance(f["line"], int):
                ff["line"] = f["line"]
            fid = f"local:{path.name}:{fp}"
            c.add("local_finding", record(fid, [f["severity"]] if f["severity"] in severities else [], **ff))
            c.relate("found_by", fid, check_id)
            if f["path"] and f"file:{f['path']}" in files:
                c.relate("located_in", fid, f"file:{f['path']}")


COLLECTORS = (
    ("repository", collect_repository),
    ("files", collect_files),
    ("python-deps", collect_python_deps),
    ("indexes", collect_indexes),
    ("workflows", collect_workflows),
    ("sops", collect_sops),
    ("env", collect_env),
    ("suppressions", collect_suppressions),
    ("local-checks", collect_local_checks),
    ("diff", collect_diff),
)


def findings_as_facts(findings, c: Collection) -> None:
    """The scanner's own checks, recorded as third-party findings with tool
    `immunis`, so a consumer treats them like any other tool's until it has
    rules of its own for them."""
    files = c.file_ids()
    for f in findings:
        digest = hashlib.sha256(f"{f.check}|{f.path}|{f.line}|{f.summary}".encode()).hexdigest()[:16]
        fields = dict(tool="immunis", tool_version=__version__, rule_id=f.check, severity=f.severity,
                      message=f.summary, fingerprint=digest)
        if f.path:
            fields["path"] = f.path
        if f.line:
            fields["line"] = f.line
        fid = f"finding:immunis:{digest}"
        c.add("third_party_finding", record(fid, [f.severity], **fields))
        if f.path and f"file:{f.path}" in files:
            c.relate("located_in", fid, f"file:{f.path}")


def scan(root: Path, config, *, project: str, ref: str | None = None, base: str | None = None,
         findings=None, environment: dict | None = None) -> dict:
    """Run every collector and build the artifact."""
    started = _now()
    repo = Repo(root, exclude=getattr(config, "exclude", ()))
    c = Collection()
    ctx: dict = {"base": base}
    for name, fn in COLLECTORS:
        try:
            fn(repo, config, c, ctx)
            c.ran.append(name)
        except Exception as e:  # noqa: BLE001 — a collector failing is a fact about the scan
            c.fail(name, f"{e.__class__.__name__}: {e}"[:200])
    if findings:
        findings_as_facts(findings, c)
    commit = ctx.get("commit") or ref or ""
    subject = {"project": project, "repository": ctx.get("repository", {"forge": "", "owner": "", "name": root.name}),
               "commit": commit, "ref": ref or ""}
    if "change" in ctx:
        subject["change"] = ctx["change"]
    finished = _now()
    return {
        "schema_version": SCHEMA_VERSION,
        "scan": {"id": f"scan:{commit or 'unknown'}:{started}", "sensor": "immunis", "sensor_version": __version__,
                 "started_at": started, "finished_at": finished, "collectors": c.ran, "failed": c.failed,
                 "environment": environment or {}},
        "subject": subject,
        "facts": c.facts,
        "relations": c.relations,
    }
